// ============================================================================
// web_server.cpp — SoftAP + captive portal + REST API
// ============================================================================
// Endpoints:
//   GET  /                Glassmorphism Web UI (PROGMEM)
//   GET  /api/status      Live telemetry snapshot (JSON)
//   POST /api/settings    Update + persist settings (JSON, capped at 2 KB)
//   POST /api/camera      scan/select/remove/pair (scan throttled server-side)
//   POST /api/command     {"cmd":"start"|"stop"|"reboot"}
//   POST /api/msp         Read-only allowlisted MSP passthrough (no GPS)
//   GET  /api/scan        Current scan results (RSSI-sorted)
//   POST /api/ota         Firmware upload (streaming handler + size cap)
//   GET  /api/ota/status  Version + heap
//   *    everything else  /api/* -> 404 JSON, other -> 302 to / (portal)
// ============================================================================

#include "web_server.h"
#include <WiFi.h>
#include <WebServer.h>
#include <DNSServer.h>
#include <Update.h>
#include <ctype.h>
#include <limits.h>
#include "config.h"
#include "settings.h"
#include "camera_manager.h"
#include "dji_camera.h"
#include "gopro_camera.h"
#include "fc_status.h"
#include "recorder.h"
#include "osd_slots.h"
#include "cam_registry.h"
#include "msp_protocol.h"
#include "scan_results.h"
#include "web_assets.h"

// ──────────────────────────────────────────────────────────────────────────────
// Internal state
// ──────────────────────────────────────────────────────────────────────────────

static WebServer _server(80);
static DNSServer _dns;
static bool      _up = false;
static char      _ipStr[16] = "192.168.4.1";
// Server-side scan throttle: last accepted POST /api/camera {"scan":true}.
// The UI also cools down client-side, but only this stops scripted radio hogs.
static uint32_t  _lastScanStartMs = 0;
// OTA upload state — set by the upload callback, reported by the response fn.
// (Never send() from inside UPLOAD_FILE_WRITE; it corrupts the connection.)
static bool      _otaActive = false;
static bool      _otaOk = false;
static char      _otaError[96] = "";
static size_t    _otaBytes = 0;
static size_t    _otaMaxBytes = 0;  // free sketch space at START (size cap)

// ──────────────────────────────────────────────────────────────────────────────
// Tiny flat-JSON readers (payloads are generated by our own UI, so a simple
// scanner is sufficient and avoids pulling in a JSON library).
//
// LIMITS: every POST body is capped at WEB_MAX_JSON_BODY_LEN (config.h) and
// checked by requireSaneBody() before parsing. Duplicate keys resolve to the
// FIRST occurrence (fail-closed); numbers are clamped to avoid long overflow.
// ──────────────────────────────────────────────────────────────────────────────

/// Reject oversized POST bodies with 413 before any String duplication.
/// Returns true when the body is safe to parse.
static bool requireSaneBody(const String &body) {
    if (body.length() > WEB_MAX_JSON_BODY_LEN) {
        _server.send(413, "application/json",
                     "{\"ok\":false,\"error\":\"body too large\"}");
        return false;
    }
    return true;
}

static int jsonKeyIndex(const String &body, const char *key) {
    // Match "key" exactly (surrounded by quotes).
    String pat = "\"";
    pat += key;
    pat += "\"";
    return body.indexOf(pat);
}

static bool jsonHas(const String &body, const char *key) {
    return jsonKeyIndex(body, key) >= 0;
}

static long jsonGetNum(const String &body, const char *key, long def = 0) {
    int i = jsonKeyIndex(body, key);
    if (i < 0) return def;
    i = body.indexOf(':', i);
    if (i < 0) return def;
    i++;
    while (i < (int)body.length() && isspace((unsigned char)body[i])) i++;
    if (i >= (int)body.length()) return def;
    bool neg = false;
    if (body[i] == '-') { neg = true; i++; }
    if (i >= (int)body.length() || !isdigit((unsigned char)body[i])) return def;
    long val = 0;
    while (i < (int)body.length() && isdigit((unsigned char)body[i])) {
        int digit = body[i] - '0';
        // Clamp on overflow instead of wrapping (fail-closed for thresholds).
        if (val > (LONG_MAX - digit) / 10) {
            return neg ? LONG_MIN : LONG_MAX;
        }
        val = val * 10 + digit;
        i++;
    }
    return neg ? -val : val;
}

static bool jsonGetBool(const String &body, const char *key, bool def = false) {
    int i = jsonKeyIndex(body, key);
    if (i < 0) return def;
    i = body.indexOf(':', i);
    if (i < 0) return def;
    // Look at the raw characters following the colon.
    int j = i + 1;
    while (j < (int)body.length() && isspace((unsigned char)body[j])) j++;
    if (body.startsWith("true", j))  return true;
    if (body.startsWith("false", j)) return false;
    return jsonGetNum(body, key, def ? 1 : 0) != 0;
}

static String jsonGetStr(const String &body, const char *key) {
    int i = jsonKeyIndex(body, key);
    if (i < 0) return "";
    i = body.indexOf(':', i);
    if (i < 0) return "";
    i = body.indexOf('"', i);          // opening quote of value
    if (i < 0) return "";
    // Find the closing quote, honouring backslash escapes (\").
    String out;
    out.reserve(32);
    for (int j = i + 1; j < (int)body.length(); j++) {
        char c = body[j];
        if (c == '\\' && j + 1 < (int)body.length()) {
            // Keep the escaped char literally (\" -> ", \\ -> \).
            out += body[++j];
        } else if (c == '"') {
            return out;
        } else {
            out += c;
        }
        if (out.length() > 64) break;  // values we care about are short
    }
    return "";  // unterminated — treat as missing
}

// ──────────────────────────────────────────────────────────────────────────────
// Handlers
// ──────────────────────────────────────────────────────────────────────────────

static void handleRoot() {
    // no-store: the UI is iterated quickly — never serve a stale cached copy.
    _server.sendHeader("Cache-Control", "no-store, must-revalidate");
    _server.sendHeader("X-Content-Type-Options", "nosniff");
    _server.sendHeader("X-Frame-Options", "DENY");
    _server.send_P(200, "text/html", INDEX_HTML);
}

static void handleStatus() {
    static char buf[2200];
    char *p = buf;
    size_t left = sizeof(buf);

    const CameraTelemetry &tel = camGetTelemetry();
    const FcTelemetry &fc = fcGetTelemetry();
    const ShutterSettings &cfg = settingsGet();

    BleConnectionState st = camGetState();
    static const char *kStateNames[] =
        {"OFF", "SCANNING", "CONNECTING", "PAIRING", "CONNECTED"};

    int batt = tel.batteryPercent <= 100 ? tel.batteryPercent : -1;

    // Saved-camera registry with live status of the active entry.
    char cams[512];
    {
        size_t o = 0;
        o += snprintf(cams + o, sizeof(cams) - o, "[");
        bool online = camIsReady();
        for (uint8_t i = 0; i < cfg.camCount; i++) {
            const SavedCamera &c = cfg.cams[i];
            const char *nm = c.name[0] ? c.name : c.mac;
            // Escape double quotes / backslashes in the name defensively.
            char safeName[sizeof(c.name)];
            strlcpy(safeName, nm, sizeof(safeName));
            for (char *q = safeName; *q; q++) {
                if (*q == '"' || *q == '\\') {
                    // +1 to move the NUL terminator too (else over-read).
                    memmove(q + 1, q, strlen(q) + 1);
                    *q = ' ';
                    q++;
                }
            }
            o += snprintf(cams + o, sizeof(cams) - o,
                          "%s{\"t\":%u,\"n\":\"%s\",\"m\":\"%s\",\"a\":%s,\"on\":%s}",
                          i ? "," : "", c.type, safeName, c.mac,
                          c.active ? "true" : "false",
                          (c.active && online) ? "true" : "false");
            if (o >= sizeof(cams) - 8) break;
        }
        o += snprintf(cams + o, sizeof(cams) - o, "]");
    }

    // Pending cams discovered in current scan (drained from BLE host task by
    // loop()). Exposed so the UI can show in-progress discoveries before they
    // land in the persisted registry. Cheap: no allocation, just strlcpy.
    // Sorted by RSSI descending (strongest first) and capped at 10 entries.
    char pending[640] = "[]";
    {
        ScanResult const *sorted[MAX_SCAN_RESULTS];
        uint8_t n = scanResultsGetSortedByRssi(sorted, MAX_SCAN_RESULTS);
        size_t o = 0;
        o += snprintf(pending + o, sizeof(pending) - o, "[");
        for (uint8_t i = 0; i < n && o < sizeof(pending) - 80; i++) {
            const char *typeStr = (sorted[i]->type == CAMERA_GOPRO) ? "GoPro" : "DJI";
            // Defensive name escape (rare but possible).
            char safeName[sizeof(sorted[i]->name)];
            strlcpy(safeName, sorted[i]->name, sizeof(safeName));
            for (char *q = safeName; *q; q++) {
                if (*q == '"' || *q == '\\') {
                    memmove(q + 1, q, strlen(q) + 1);  // include NUL
                    *q = ' ';
                    q++;
                }
            }
            o += snprintf(pending + o, sizeof(pending) - o,
                "%s{\"mac\":\"%s\",\"n\":\"%s\",\"t\":\"%s\",\"r\":%d}",
                i ? "," : "", sorted[i]->mac, safeName, typeStr, sorted[i]->rssi);
        }
        if (o < sizeof(pending) - 1) snprintf(pending + o, sizeof(pending) - o, "]");
    }

    // Last connect-attempt error from the active backend (empty = no error).
    // The Web UI shows it as a toast and clears the field on next success.
    const char *lastErr = "";
    if (cfg.camera == CAMERA_DJI)  lastErr = djiGetLastError();
    else if (cfg.camera == CAMERA_GOPRO) lastErr = gpGetLastError();
    char safeErr[64] = "";
    {
        size_t i = 0;
        for (; lastErr[i] && i < sizeof(safeErr) - 1; i++) {
            char ch = lastErr[i];
            safeErr[i] = (ch == '"' || ch == '\\') ? ' ' : ch;
        }
        safeErr[i] = '\0';
    }

    // heap at top level so the UI can show/monitor it. The sys.heap field
    // is kept for backward compatibility.
    uint32_t heap = ESP.getFreeHeap();

    size_t w = snprintf(p, left,
        "{\"heap\":%u,"
        "\"cam\":{\"type\":%d,\"name\":\"%s\",\"state\":%d,"
        "\"stateName\":\"%s\",\"batt\":%d,\"recTime\":%u,\"valid\":%s,"
        "\"model\":\"%s\"},"
        "\"rec\":{\"desired\":%s,\"switchOn\":%s,\"roa\":%s,\"rcValue\":%u,"
        "\"auxCh\":%u,\"thr\":%u,\"deb\":%u},"
        "\"slots\":[%d,%d,%d,%d],"
        "\"osd\":[\"%s\",\"%s\",\"%s\",\"%s\"],"
        "\"wifiSwitch\":%d,\"wifiOn\":%s,\"scanAll\":%s,"
        "\"lastError\":\"%s\","
        "\"cams\":%s,\"pending_cams\":%s,\"scanning\":%s,"
        "\"fc\":{\"alive\":%s,\"armed\":%s,\"vbat10\":%u,\"rssi\":%u,"
        "\"cycle\":%u,\"api\":\"%s\",\"fw\":\"%s\",\"board\":\"%s\"},"
        "\"sys\":{\"heap\":%u,\"uptime\":%lu,\"ip\":\"%s\",\"sta\":%d,\"version\":\"%s\"}}",
        heap,
        (int)cfg.camera, camGetName(), (int)st, kStateNames[st], batt,
        tel.recTimeSeconds, tel.dataValid ? "true" : "false", tel.model,
        recorderDesiredRecording() ? "true" : "false",
        recorderSwitchOn() ? "true" : "false",
        cfg.recordOnArm ? "true" : "false",
        recorderLastRcValue(),
        cfg.auxChannelIndex, cfg.rcThresholdUs, cfg.debounceMs,
        cfg.osdSlot[0], cfg.osdSlot[1], cfg.osdSlot[2], cfg.osdSlot[3],
        osdSlotText(0), osdSlotText(1), osdSlotText(2), osdSlotText(3),
        (cfg.wifiSwitchCh <= 15) ? (int)cfg.wifiSwitchCh : -1,
        _up ? "true" : "false",
        cfg.scanAll ? "true" : "false",
        safeErr,
        cams, pending,
        scanResultsIsScanning() ? "true" : "false",
        fc.fcAlive ? "true" : "false", fc.armed ? "true" : "false",
        fc.vbat10, fc.rssi / 10, fc.cycleTimeUs,
        fcApiVersion(), fcFirmwareVersion(), fcBoardName(),
        heap, millis() / 1000UL, _ipStr,
        WiFi.softAPgetStationNum(),
        FIRMWARE_VERSION);
    if (w >= left) {
        // Buffer exhausted — fail closed with a minimal valid payload rather
        // than sending truncated JSON that breaks the UI parser.
        snprintf(buf, sizeof(buf),
                 "{\"ok\":false,\"error\":\"status truncated\"}");
    }

    _server.sendHeader("Cache-Control", "no-store");
    _server.sendHeader("X-Content-Type-Options", "nosniff");
    _server.send(200, "application/json", buf);
}

static void sendJsonError(const char *msg) {
    char buf[128];
    snprintf(buf, sizeof(buf), "{\"ok\":false,\"error\":\"%s\"}", msg);
    _server.send(400, "application/json", buf);
}

static void handleSettingsPost() {
    String body = _server.arg("plain");
    if (!requireSaneBody(body)) return;

    if (!jsonHas(body, "camera") && !jsonHas(body, "auxChannel") &&
        !jsonHas(body, "recordOnArm") && !jsonHas(body, "ssid") &&
        !jsonHas(body, "slot0") && !jsonHas(body, "slot1") &&
        !jsonHas(body, "slot2") && !jsonHas(body, "slot3") &&
        !jsonHas(body, "wifiSwitch") && !jsonHas(body, "scanAll") &&
        !jsonHas(body, "threshold") && !jsonHas(body, "debounce") &&
        !jsonHas(body, "stopOnDisarm")) {
        sendJsonError("no recognized keys");
        return;
    }

    ShutterSettings &cfg = settingsGet();
    bool apNeedsRestart = false;

    // Camera brand
    if (jsonHas(body, "camera")) {
        long cam = jsonGetNum(body, "camera");
        if (cam == CAMERA_GOPRO && cfg.camera != CAMERA_GOPRO) {
            camSetCamera(CAMERA_GOPRO);
        } else if (cam == CAMERA_DJI && cfg.camera != CAMERA_DJI) {
            camSetCamera(CAMERA_DJI);
        } else if (cam != CAMERA_DJI && cam != CAMERA_GOPRO) {
            sendJsonError("invalid camera type");
            return;
        }
    }

    // Record switch
    if (jsonHas(body, "auxChannel")) {
        long ch = jsonGetNum(body, "auxChannel");
        if (ch < 0 || ch > 15) { sendJsonError("channel out of range"); return; }
        cfg.auxChannelIndex = (uint8_t)ch;
    }
    if (jsonHas(body, "threshold")) {
        long t = jsonGetNum(body, "threshold");
        if (t < 1200 || t > 1800) { sendJsonError("threshold out of range"); return; }
        cfg.rcThresholdUs = (uint16_t)t;
    }
    if (jsonHas(body, "debounce")) {
        long d = jsonGetNum(body, "debounce");
        if (d < 50 || d > 1000) { sendJsonError("debounce out of range"); return; }
        cfg.debounceMs = (uint16_t)d;
    }

    // Behaviour toggles
    if (jsonHas(body, "recordOnArm"))
        cfg.recordOnArm = jsonGetBool(body, "recordOnArm");
    if (jsonHas(body, "stopOnDisarm"))
        cfg.stopOnDisarm = jsonGetBool(body, "stopOnDisarm");

    // "Show all nearby devices" toggle (NVS-persisted, no AP restart).
    if (jsonHas(body, "scanAll"))
        cfg.scanAll = jsonGetBool(body, "scanAll");

    // Wi-Fi radio switch channel (-1 or 255 = disabled)
    if (jsonHas(body, "wifiSwitch")) {
        long ch = jsonGetNum(body, "wifiSwitch");
        if ((ch >= 0 && ch <= 15) || ch == -1) {
            cfg.wifiSwitchCh = (ch == -1) ? 255 : (uint8_t)ch;
        } else {
            sendJsonError("wifi switch channel out of range");
            return;
        }
    }

    // OSD slots
    for (uint8_t s = 0; s < 4; s++) {
        char key[8];
        snprintf(key, sizeof(key), "slot%d", s);
        if (jsonHas(body, key)) {
            long v = jsonGetNum(body, key);
            if (v < 0 || v >= OSD_SLOT_COUNT) {
                sendJsonError("invalid slot content");
                return;
            }
            cfg.osdSlot[s] = (uint8_t)v;
        }
    }

    // Wi-Fi credentials
    if (jsonHas(body, "ssid")) {
        String ssid = jsonGetStr(body, "ssid");
        ssid.trim();
        if (ssid.length() < 1 || ssid.length() > WIFI_AP_SSID_MAX_LEN) {
            sendJsonError("SSID must be 1-32 chars");
            return;
        }
        strlcpy(cfg.apSsid, ssid.c_str(), sizeof(cfg.apSsid));
        apNeedsRestart = true;
    }
    if (jsonHas(body, "pass")) {
        String pass = jsonGetStr(body, "pass");
        pass.trim();
        // WPA2-PSK is 8..63 chars. Empty (open AP) is rejected on POST —
        // use the serial console for recovery instead of one-click de-auth.
        if (pass.length() < WIFI_AP_PASS_MIN_LEN ||
            pass.length() > WIFI_AP_PASS_MAX_LEN) {
            sendJsonError("password must be 8-63 chars");
            return;
        }
        strlcpy(cfg.apPass, pass.c_str(), sizeof(cfg.apPass));
        apNeedsRestart = true;
    }

    settingsSave();
    DBG("WEB: settings saved");

    if (apNeedsRestart) {
        _server.send(200, "application/json",
                     "{\"ok\":true,\"apRestart\":true}");
        delay(200);  // Let the response flush (short; don't wedge loop)
        // webStart() early-returns while _up — stop first so new creds apply.
        webStop();
        delay(100);
        webStart();
        return;
    }

    _server.send(200, "application/json", "{\"ok\":true}");
}

static void handleCommand() {
    String body = _server.arg("plain");
    if (!requireSaneBody(body)) return;
    String cmd = jsonGetStr(body, "cmd");

    if (cmd == "start") {
        recorderManualStart();
        _server.send(200, "application/json", "{\"ok\":true}");
    } else if (cmd == "stop") {
        recorderManualStop();
        _server.send(200, "application/json", "{\"ok\":true}");
    } else if (cmd == "reboot") {
        _server.send(200, "application/json", "{\"ok\":true}");
        delay(200);
        ESP.restart();
    } else {
        sendJsonError("unknown command");
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Saved-camera registry endpoints:  POST /api/camera {"select":i} | {"remove":i}
// ──────────────────────────────────────────────────────────────────────────────

static void handleCameraPost() {
    String body = _server.arg("plain");
    if (!requireSaneBody(body)) return;

    if (jsonHas(body, "scan")) {
        // {"scan": true} — user-initiated discovery scan.
        // Refuse to start a second scan while one is in progress so the
        // 5 s window is not split across two competing jobs on the radio.
        if (scanResultsIsScanning()) {
            // Graceful degradation: tell the UI we are already scanning,
            // don't throw 400.
            _server.send(200, "application/json", "{\"ok\":true,\"already\":true}");
            return;
        }
        // Server-side throttle: block scripted scan floods that would hog
        // the single 2.4 GHz radio (BLE scan duty + SoftAP beacons).
        uint32_t now = millis();
        if (_lastScanStartMs != 0 && now - _lastScanStartMs < WEB_SCAN_COOLDOWN_MS) {
            _server.send(429, "application/json",
                         "{\"ok\":false,\"error\":\"scan cooldown, try again shortly\"}");
            return;
        }
        _lastScanStartMs = now;
        camStartUserScan();
        _server.send(200, "application/json", "{\"ok\":true}");
    } else if (jsonHas(body, "select")) {
        long idx = jsonGetNum(body, "select", -1);
        if (idx < 0 || !camRegistrySelect((uint8_t)idx)) {
            sendJsonError("invalid camera index");
            return;
        }
        camKick();   // Stop scanning, connect to the selected MAC right away
        _server.send(200, "application/json", "{\"ok\":true}");
    } else if (jsonHas(body, "remove")) {
        long idx = jsonGetNum(body, "remove", -1);
        if (idx < 0 || !camRegistryRemove((uint8_t)idx)) {
            sendJsonError("invalid camera index");
            return;
        }
        // Also disconnect BLE if removing the active camera
        camDisconnect();
        _server.send(200, "application/json", "{\"ok\":true}");
    } else if (jsonHas(body, "pair")) {
        // "pair" body: {"mac":"AA:BB:...","type":0|1}
        String mac = jsonGetStr(body, "mac");
        long type = jsonGetNum(body, "type", -1);
        
        // Security: Validate MAC format strictly (17 chars, XX:XX:XX:XX:XX:XX)
        if (mac.length() != 17) {
            sendJsonError("pair: invalid MAC length");
            return;
        }
        for (int i = 0; i < 17; i++) {
            char c = mac.charAt(i);
            if (i % 3 == 2) {
                if (c != ':') {
                    sendJsonError("pair: invalid MAC format");
                    return;
                }
            } else {
                if (!isHexadecimalDigit(c)) {
                    sendJsonError("pair: invalid MAC character");
                    return;
                }
            }
        }
        
        if ((type != CAMERA_DJI && type != CAMERA_GOPRO)) {
            sendJsonError("pair: mac and type required");
            return;
        }
        
        // Check if device is currently visible in scan results (online check).
        // Uses the same live scan-results table that /api/scan serves, so a
        // device shown in the Discover card is always pairable.
        ScanResult const *sorted[MAX_SCAN_RESULTS];
        uint8_t scount = scanResultsGetSortedByRssi(sorted, MAX_SCAN_RESULTS);
        bool isOnline = false;
        char nameBuf[24] = "";
        for (uint8_t i = 0; i < scount; i++) {
            if (strcasecmp(sorted[i]->mac, mac.c_str()) == 0 &&
                sorted[i]->type == (uint8_t)type) {
                isOnline = true;
                // Sanitize device name to prevent XSS
                sanitizeDeviceName(nameBuf, sorted[i]->name, sizeof(nameBuf));
                break;
            }
        }
        // Don't allow pairing with offline devices
        if (!isOnline) {
            sendJsonError("Cannot pair: device is offline or not in range");
            return;
        }
        if (!camRegistrySave((uint8_t)type, mac.c_str(),
                              nameBuf[0] ? nameBuf : mac.c_str())) {
            sendJsonError("pair: registry full or invalid");
            return;
        }
        // Find the newly-saved entry's index and select+kick it.
        for (uint8_t i = 0; i < settingsGet().camCount; i++) {
            if (strcasecmp(settingsGet().cams[i].mac, mac.c_str()) == 0 &&
                settingsGet().cams[i].type == (uint8_t)type) {
                camRegistrySelect(i);
                camKick();
                break;
            }
        }
        _server.send(200, "application/json", "{\"ok\":true}");
    } else {
        sendJsonError("expected scan, select, remove, or pair");
    }
}

// MSP passthrough — lets the Web UI talk MSP directly to the FC.
// Read-only allowlist: safe introspection commands only.  This is the
// foundation for a future browser-side "configurator-lite" panel.
//
// PRIVACY NOTE: MSP_RAW_GPS (108) is deliberately NOT exposed — GPS/position
// over unauthenticated Wi-Fi is a tracking risk. Altitude (109) stays because
// the Dashboard MSP console offers it and it carries no position fix.
// ──────────────────────────────────────────────────────────────────────────────

// Named MSP codes used by the allowlist (see msp_protocol.h for the rest).
static const uint16_t kMspBuildInfo    = 5;
static const uint16_t kMspMotor        = 104;
static const uint16_t kMspAltitude     = 109;
static const uint16_t kMspBoxNames     = 116;
static const uint16_t kMspBatteryState = 130;

static bool mspCmdAllowed(uint16_t cmd) {
    static const uint16_t kAllowed[] = {
        MSP_API_VERSION,   // 1
        MSP_FC_VARIANT,    // 2
        MSP_FC_VERSION,    // 3
        MSP_BOARD_INFO,    // 4
        kMspBuildInfo,     // 5
        MSP_STATUS,        // 101
        kMspMotor,         // 104
        MSP_RC,            // 105
        kMspAltitude,      // 109 (no GPS: see note above)
        MSP_ANALOG,        // 110
        kMspBoxNames,      // 116
        MSP_BOXIDS,        // 119
        kMspBatteryState,  // 130
    };
    for (size_t i = 0; i < sizeof(kAllowed) / sizeof(kAllowed[0]); i++) {
        if (kAllowed[i] == cmd) return true;
    }
    return false;
}

static void handleMspPost() {
    String body = _server.arg("plain");
    if (!requireSaneBody(body)) return;
    long cmd = jsonGetNum(body, "cmd", -1);

    if (cmd < 0 || cmd > 255) {
        sendJsonError("missing/invalid cmd");
        return;
    }
    if (!mspCmdAllowed((uint16_t)cmd)) {
        sendJsonError("command not in read-only allowlist");
        return;
    }

    // Flush any stale bytes, then send the request and wait for the reply.
    // Safe here: we run inside loop()'s call stack (single-threaded), and the
    // main-loop parser simply resyncs on '$' afterwards.
    while (Serial1.available()) Serial1.read();

    mspSendRequest((uint8_t)cmd);

    MspMessage msg;
    uint32_t started = millis();
    bool got = false;
    while (millis() - started < MSP_RESPONSE_TIMEOUT_MS) {
        while (Serial1.available()) {
            uint8_t b = Serial1.read();
            if (mspParseByte(b, msg)) {
                fcStatusFeed(msg);          // Keep live stats fresh
                if ((uint16_t)msg.cmd == (uint16_t)cmd && msg.valid && !msg.isError) {
                    got = true;
                    break;
                }
            }
        }
        if (got) break;
        delay(2);
        yield();
    }

    if (!got) {
        _server.send(504, "application/json",
                     "{\"ok\":false,\"error\":\"FC timeout\"}");
        return;
    }

    // Hex-encode the payload.
    static char hex[MSP_MAX_PAYLOAD_SIZE * 3 + 4];
    size_t o = 0;
    for (uint8_t i = 0; i < msg.payloadSize; i++) {
        o += snprintf(hex + o, sizeof(hex) - o, "%02X", msg.payload[i]);
    }
    hex[o] = '\0';

    char out[192];
    snprintf(out, sizeof(out),
             "{\"ok\":true,\"cmd\":%u,\"len\":%u,\"payload\":\"%s\"}",
             (unsigned)msg.cmd, (unsigned)msg.payloadSize, hex);
    _server.send(200, "application/json", out);
}

// ──────────────────────────────────────────────────────────────────────────────
// Scan Results Endpoint
// ──────────────────────────────────────────────────────────────────────────────

static void handleScanResults() {
    // Serve the REAL scan-results table (populated directly by the BLE
    // scan callbacks, sorted strongest-RSSI first) — not the cam_registry
    // discovered list, which is fed through a single-slot "newest wins"
    // funnel and drops all but the last advertiser.
    ScanResult const *sorted[MAX_SCAN_RESULTS];
    uint8_t n = scanResultsGetSortedByRssi(sorted, MAX_SCAN_RESULTS);

    static char buf[4096];
    char *p = buf;
    size_t left = sizeof(buf);

    size_t w = snprintf(p, left, "{\"scanning\":%s,\"results\":[",
                        scanResultsIsScanning() ? "true" : "false");
    p += w; left -= w;

    // Field names match what the Web UI's renderDiscovered() reads:
    // r.mac, r.n (name), r.t (type STRING 'GoPro'/'DJI'), r.rssi.
    for (uint8_t i = 0; i < n && left > 96; i++) {
        if (i > 0) { *p++ = ','; left--; }

        // Sanitize device name before sending to client (prevent XSS)
        char sanitizedName[24] = "";
        sanitizeDeviceName(sanitizedName, sorted[i]->name, sizeof(sanitizedName));

        const char *typeStr = (sorted[i]->type == CAMERA_GOPRO) ? "GoPro" : "DJI";
        w = snprintf(p, left,
                     "{\"mac\":\"%s\",\"n\":\"%s\",\"t\":\"%s\",\"rssi\":%d}",
                     sorted[i]->mac, sanitizedName, typeStr, sorted[i]->rssi);
        p += w; left -= w;
    }

    // Close the array and the object — without this the JSON is invalid,
    // r.json() throws in the browser, and the Discover card stays empty.
    if (left > 2) { snprintf(p, left, "]}"); }
    else { snprintf(buf, sizeof(buf), "{\"scanning\":false,\"results\":[]}"); }

    _server.sendHeader("Cache-Control", "no-store");
    _server.sendHeader("X-Content-Type-Options", "nosniff");
    _server.send(200, "application/json", buf);
}

// ──────────────────────────────────────────────────────────────────────────────
// OTA Firmware Update Endpoint
// ──────────────────────────────────────────────────────────────────────────────
// Correct ESP32 WebServer pattern: one UPLOAD callback streams the bytes,
// one RESPONSE callback sends the single final JSON. Never send() from
// inside UPLOAD_FILE_START/WRITE — it corrupts the upload connection.
//
// SECURITY STATUS (be honest): this endpoint has NO auth and NO signature
// check — anyone joined to the AP can flash firmware. Mitigations in place:
//   • size cap (rejects images larger than free sketch space),
//   • Update.abort() on any error (no wedged half-flash),
//   • single final response (no mid-upload sends).
// Full fix (admin session + ECDSA signature) is roadmap — see README.
// ──────────────────────────────────────────────────────────────────────────────

static void handleOtaUpload() {
    HTTPUpload& upload = _server.upload();

    if (upload.status == UPLOAD_FILE_START) {
        _otaActive = true;
        _otaOk = false;
        _otaError[0] = '\0';
        _otaBytes = 0;
        _otaMaxBytes = ESP.getFreeSketchSpace();
        Serial.printf("OTA Start: %s\n", upload.filename.c_str());

        if (_otaMaxBytes == 0) {
            snprintf(_otaError, sizeof(_otaError), "no space for update");
            Update.abort();
            _otaActive = false;
            return;
        }
        if (!Update.begin(UPDATE_SIZE_UNKNOWN)) {
            snprintf(_otaError, sizeof(_otaError), "Begin failed");
            Serial.printf("OTA Begin Error: %s\n", Update.errorString());
            Update.abort();
            _otaActive = false;
        }
    } else if (upload.status == UPLOAD_FILE_WRITE) {
        if (!_otaActive) return;  // begin already failed — drain silently
        // Incremental size cap: never write past free sketch space.
        if (_otaBytes + upload.currentSize > _otaMaxBytes) {
            snprintf(_otaError, sizeof(_otaError), "image too large");
            Update.abort();
            _otaActive = false;
            return;
        }
        if (Update.write(upload.buf, upload.currentSize) != upload.currentSize) {
            snprintf(_otaError, sizeof(_otaError), "Write failed");
            Serial.printf("OTA Write Error: %s\n", Update.errorString());
            Update.abort();
            _otaActive = false;
        } else {
            _otaBytes += upload.currentSize;
        }
    } else if (upload.status == UPLOAD_FILE_END) {
        if (_otaActive && Update.end(true)) {
            Serial.printf("OTA Success: %u bytes written\n", upload.totalSize);
            _otaOk = true;
        } else {
            if (!_otaError[0]) snprintf(_otaError, sizeof(_otaError), "End failed");
            Serial.printf("OTA End Error: %s\n", Update.errorString());
            Update.abort();
            _otaActive = false;
        }
    } else if (upload.status == UPLOAD_FILE_ABORTED) {
        Update.abort();
        _otaActive = false;
        snprintf(_otaError, sizeof(_otaError), "upload aborted");
    }
}

static void handleOtaResponse() {
    _server.sendHeader("Connection", "close");
    if (_otaOk) {
        _otaOk = false;
        _server.send(200, "application/json",
            "{\"ok\":true,\"message\":\"Firmware updated! Rebooting...\"}");
        delay(200);
        ESP.restart();
    } else {
        char out[160];
        snprintf(out, sizeof(out), "{\"ok\":false,\"error\":\"%s\"}",
                 _otaError[0] ? _otaError : "update failed");
        _otaError[0] = '\0';
        _server.send(500, "application/json", out);
    }
}

static void handleOtaStatus() {
    char out[128];
    snprintf(out, sizeof(out), 
        "{\"ok\":true,\"version\":\"%s\",\"free_heap\":%lu}",
        FIRMWARE_VERSION, (unsigned long)ESP.getFreeHeap());
    _server.send(200, "application/json", out);
}

static void redirectToRoot() {
    String uri = _server.uri();
    // API paths must fail closed with JSON (not a 302 to HTML) so wrong-method
    // probes and scripts can't be hidden behind the captive-portal redirect.
    if (uri.startsWith("/api/")) {
        _server.send(404, "application/json",
                     "{\"ok\":false,\"error\":\"not found\"}");
        return;
    }
    _server.sendHeader(String("Location"), String("http://") + _ipStr + "/", true);
    _server.send(302, "text/plain", "");
}

// ── OS captive-portal probe handlers ─────────────────────────────────────────
// Each OS probes a known URL to detect "internet available".  Answering these
// with their expected SUCCESS bodies makes Windows/iOS/Android mark the
// network as usable immediately — no scary errors, no blocked popups.  Any
// other hostname still lands on our UI via the onNotFound redirect.

static const char NCSI_SUCCESS[] =
    "Microsoft Connect Test";

static void handleProbeConnectTest() {          // Windows: /connecttest.txt
    _server.send(200, "text/plain", NCSI_SUCCESS);
}

static void handleProbeNcsi() {                 // Windows legacy: /ncsi.txt
    _server.send(200, "text/plain", "Microsoft NCSI");
}

static void handleProbe204() {                  // Android: /generate_204
    _server.send(204, "text/plain", "");
}

static void handleProbeApple() {                // iOS/macOS: /hotspot-detect.html
    _server.send(200, "text/html",
                 "<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>");
}

// ──────────────────────────────────────────────────────────────────────────────
// Lifecycle
// ──────────────────────────────────────────────────────────────────────────────

void webStart() {
    const ShutterSettings &cfg = settingsGet();
    if (_up) return;   // Already running

    WiFi.persistent(false);              // Keep Wi-Fi creds out of NVS
    WiFi.mode(WIFI_AP);
    delay(50);

    // Deterministic AP address: 192.168.4.1/24 (matches UI + captive portal).
    IPAddress localIp(192, 168, 4, 1);
    IPAddress gateway(192, 168, 4, 1);
    IPAddress subnet(255, 255, 255, 0);
    WiFi.softAPConfig(localIp, gateway, subnet);

    // WPA2 needs 8..63 chars. Shorter stored passwords (e.g. legacy open or
    // truncated entries) fall back to OPEN with a loud log — the POST path
    // already rejects new weak passwords (see handleSettingsPost).
    size_t passLen = strlen(cfg.apPass);
    bool havePass = (passLen >= WIFI_AP_PASS_MIN_LEN &&
                     passLen <= WIFI_AP_PASS_MAX_LEN);
    bool ok;
    if (havePass) {
        ok = WiFi.softAP(cfg.apSsid, cfg.apPass);
    } else {
        ok = WiFi.softAP(cfg.apSsid);   // Open network
    }
    if (!ok) {
        DBG("WEB: SoftAP failed — retrying once");
        delay(200);
        ok = havePass ? WiFi.softAP(cfg.apSsid, cfg.apPass)
                      : WiFi.softAP(cfg.apSsid);
    }
    if (!ok) {
        DBG("WEB: SoftAP failed twice!");
        _up = false;
        return;
    }

    strlcpy(_ipStr, localIp.toString().c_str(), sizeof(_ipStr));

    // Captive DNS: every hostname resolves to us.
    _dns.stop();
    _dns.setErrorReplyCode(DNSReplyCode::NoError);
    if (!_dns.start(53, "*", localIp)) {
        DBG("WEB: captive DNS failed to start");
    }

    _server.stop();
    _server.on("/",               HTTP_GET,  handleRoot);
    _server.on("/api/status",     HTTP_GET,  handleStatus);
    _server.on("/api/settings",   HTTP_POST, handleSettingsPost);
    _server.on("/api/camera",     HTTP_POST, handleCameraPost);
    _server.on("/api/command",    HTTP_POST, handleCommand);
    _server.on("/api/msp",        HTTP_POST, handleMspPost);
    _server.on("/api/scan",       HTTP_GET,  handleScanResults);
    // OTA needs the two-callback form: response fn + upload-streaming fn.
    _server.on("/api/ota", HTTP_POST, handleOtaResponse, handleOtaUpload);
    _server.on("/api/ota/status", HTTP_GET,  handleOtaStatus);

    // OS connectivity probes → answer with SUCCESS bodies (see handlers above).
    _server.on("/connecttest.txt",              HTTP_GET, handleProbeConnectTest);
    _server.on("/ncsi.txt",                     HTTP_GET, handleProbeNcsi);
    _server.on("/generate_204",                 HTTP_GET, handleProbe204);
    _server.on("/gen_204",                      HTTP_GET, handleProbe204);
    _server.on("/hotspot-detect.html",          HTTP_GET, handleProbeApple);
    _server.on("/library/test/success.html",    HTTP_GET, handleProbeApple);
    // Anything else (any hostname, any path) → our UI.
    _server.onNotFound(redirectToRoot);

    _server.begin();
    _up = true;

    DBG("WEB: AP '%s' up — http://%s/ (open=%s)",
        cfg.apSsid, _ipStr, havePass ? "false" : "true");
}

void webStop() {
    if (!_up) return;
    _dns.stop();
    _server.stop();
    WiFi.softAPdisconnect(true);
    WiFi.mode(WIFI_OFF);          // Powers down the Wi-Fi radio (BLE unaffected)
    _up = false;
    DBG("WEB: Wi-Fi powered off (radio switch)");
}

void webInit() {
    // Boot-time entry point.  Always starts the AP so the user can never be
    // locked out; a configured radio switch turns it off once RC data flows.
    webStart();
}

void webUpdate() {
    if (!_up) return;
    _dns.processNextRequest();
    _server.handleClient();
}

const char* webApIp() { return _ipStr; }
bool webIsUp()        { return _up; }
