// ============================================================================
// web_server.cpp — SoftAP + captive portal + REST API
// ============================================================================
// Endpoints:
//   GET  /                Glassmorphism Web UI (PROGMEM)
//   GET  /api/status      Live telemetry snapshot (JSON)
//   POST /api/settings    Update + persist settings (JSON)
//   POST /api/command     {"cmd":"start"|"stop"|"reboot"}
//   *    everything else  Redirect to / (captive portal behaviour)
// ============================================================================

#include "web_server.h"
#include <WiFi.h>
#include <WebServer.h>
#include <DNSServer.h>
#include "config.h"
#include "settings.h"
#include "camera_manager.h"
#include "dji_camera.h"
#include "gopro_camera.h"
#include "fc_status.h"
#include "recorder.h"
#include "osd_slots.h"
#include "cam_registry.h"
#include "msp_protocol.h"
#include "scan_results.h"
#include "web_assets.h"

// ──────────────────────────────────────────────────────────────────────────────
// Internal state
// ──────────────────────────────────────────────────────────────────────────────

static WebServer _server(80);
static DNSServer _dns;
static bool      _up = false;
static char      _ipStr[16] = "192.168.4.1";

// ──────────────────────────────────────────────────────────────────────────────
// Tiny flat-JSON readers (payloads are generated by our own UI, so a simple
// scanner is sufficient and avoids pulling in a JSON library).
// ──────────────────────────────────────────────────────────────────────────────

static int jsonKeyIndex(const String &body, const char *key) {
    // Match "key" exactly (surrounded by quotes).
    String pat = "\"";
    pat += key;
    pat += "\"";
    return body.indexOf(pat);
}

static bool jsonHas(const String &body, const char *key) {
    return jsonKeyIndex(body, key) >= 0;
}

static long jsonGetNum(const String &body, const char *key, long def = 0) {
    int i = jsonKeyIndex(body, key);
    if (i < 0) return def;
    i = body.indexOf(':', i);
    if (i < 0) return def;
    i++;
    while (i < (int)body.length() && isspace((unsigned char)body[i])) i++;
    bool neg = false;
    if (body[i] == '-') { neg = true; i++; }
    long val = 0;
    while (i < (int)body.length() && isdigit((unsigned char)body[i])) {
        val = val * 10 + (body[i] - '0');
        i++;
    }
    return neg ? -val : val;
}

static bool jsonGetBool(const String &body, const char *key, bool def = false) {
    int i = jsonKeyIndex(body, key);
    if (i < 0) return def;
    i = body.indexOf(':', i);
    if (i < 0) return def;
    // Look at the raw characters following the colon.
    int j = i + 1;
    while (j < (int)body.length() && isspace((unsigned char)body[j])) j++;
    if (body.startsWith("true", j))  return true;
    if (body.startsWith("false", j)) return false;
    return jsonGetNum(body, key, def ? 1 : 0) != 0;
}

static String jsonGetStr(const String &body, const char *key) {
    int i = jsonKeyIndex(body, key);
    if (i < 0) return "";
    i = body.indexOf(':', i);
    if (i < 0) return "";
    i = body.indexOf('"', i);          // opening quote of value
    if (i < 0) return "";
    int j = body.indexOf('"', i + 1);
    if (j < 0) return "";
    return body.substring(i + 1, j);
}

// ──────────────────────────────────────────────────────────────────────────────
// Handlers
// ──────────────────────────────────────────────────────────────────────────────

static void handleRoot() {
    // no-store: the UI is iterated quickly — never serve a stale cached copy.
    _server.sendHeader("Cache-Control", "no-store, must-revalidate");
    _server.send_P(200, "text/html", INDEX_HTML);
}

static void handleStatus() {
    static char buf[2200];
    char *p = buf;
    size_t left = sizeof(buf);

    const CameraTelemetry &tel = camGetTelemetry();
    const FcTelemetry &fc = fcGetTelemetry();
    const ShutterSettings &cfg = settingsGet();

    BleConnectionState st = camGetState();
    static const char *kStateNames[] =
        {"OFF", "SCANNING", "CONNECTING", "PAIRING", "CONNECTED"};

    int batt = tel.batteryPercent <= 100 ? tel.batteryPercent : -1;

    // Saved-camera registry with live status of the active entry.
    char cams[512];
    {
        size_t o = 0;
        o += snprintf(cams + o, sizeof(cams) - o, "[");
        bool online = camIsReady();
        for (uint8_t i = 0; i < cfg.camCount; i++) {
            const SavedCamera &c = cfg.cams[i];
            const char *nm = c.name[0] ? c.name : c.mac;
            // Escape double quotes / backslashes in the name defensively.
            char safeName[sizeof(c.name)];
            strlcpy(safeName, nm, sizeof(safeName));
            for (char *q = safeName; *q; q++) {
                if (*q == '"' || *q == '\\') { memmove(q + 1, q, strlen(q)); *q = ' '; q++; }
            }
            o += snprintf(cams + o, sizeof(cams) - o,
                          "%s{\"t\":%u,\"n\":\"%s\",\"m\":\"%s\",\"a\":%s,\"on\":%s}",
                          i ? "," : "", c.type, safeName, c.mac,
                          c.active ? "true" : "false",
                          (c.active && online) ? "true" : "false");
            if (o >= sizeof(cams) - 8) break;
        }
        o += snprintf(cams + o, sizeof(cams) - o, "]");
    }

    // Pending cams discovered in current scan (drained from BLE host task by
    // loop()). Exposed so the UI can show in-progress discoveries before they
    // land in the persisted registry. Cheap: no allocation, just strlcpy.
    // Sorted by RSSI descending (strongest first) and capped at 10 entries.
    char pending[640] = "[]";
    {
        ScanResult const *sorted[MAX_SCAN_RESULTS];
        uint8_t n = scanResultsGetSortedByRssi(sorted, MAX_SCAN_RESULTS);
        size_t o = 0;
        o += snprintf(pending + o, sizeof(pending) - o, "[");
        for (uint8_t i = 0; i < n && o < sizeof(pending) - 80; i++) {
            const char *typeStr = (sorted[i]->type == CAMERA_GOPRO) ? "GoPro" : "DJI";
            // Defensive name escape (rare but possible).
            char safeName[sizeof(sorted[i]->name)];
            strlcpy(safeName, sorted[i]->name, sizeof(safeName));
            for (char *q = safeName; *q; q++) {
                if (*q == '"' || *q == '\\') { memmove(q + 1, q, strlen(q)); *q = ' '; q++; }
            }
            o += snprintf(pending + o, sizeof(pending) - o,
                "%s{\"mac\":\"%s\",\"n\":\"%s\",\"t\":\"%s\",\"r\":%d}",
                i ? "," : "", sorted[i]->mac, safeName, typeStr, sorted[i]->rssi);
        }
        if (o < sizeof(pending) - 1) snprintf(pending + o, sizeof(pending) - o, "]");
    }

    // Last connect-attempt error from the active backend (empty = no error).
    // The Web UI shows it as a toast and clears the field on next success.
    const char *lastErr = "";
    if (cfg.camera == CAMERA_DJI)  lastErr = djiGetLastError();
    else if (cfg.camera == CAMERA_GOPRO) lastErr = gpGetLastError();
    char safeErr[64] = "";
    {
        size_t i = 0;
        for (; lastErr[i] && i < sizeof(safeErr) - 1; i++) {
            char ch = lastErr[i];
            safeErr[i] = (ch == '"' || ch == '\\') ? ' ' : ch;
        }
        safeErr[i] = '\0';
    }

    // heap at top level so the UI can show/monitor it. The sys.heap field
    // is kept for backward compatibility.
    uint32_t heap = ESP.getFreeHeap();

    size_t w = snprintf(p, left,
        "{\"heap\":%u,"
        "\"cam\":{\"type\":%d,\"name\":\"%s\",\"state\":%d,"
        "\"stateName\":\"%s\",\"batt\":%d,\"recTime\":%u,\"valid\":%s,"
        "\"model\":\"%s\"},"
        "\"rec\":{\"desired\":%s,\"switchOn\":%s,\"roa\":%s,\"rcValue\":%u,"
        "\"auxCh\":%u,\"thr\":%u,\"deb\":%u},"
        "\"slots\":[%d,%d,%d,%d],"
        "\"osd\":[\"%s\",\"%s\",\"%s\",\"%s\"],"
        "\"wifiSwitch\":%d,\"wifiOn\":%s,\"scanAll\":%s,"
        "\"lastError\":\"%s\","
        "\"cams\":%s,\"pending_cams\":%s,\"scanning\":%s,"
        "\"fc\":{\"alive\":%s,\"armed\":%s,\"vbat10\":%u,\"rssi\":%u,"
        "\"cycle\":%u,\"api\":\"%s\",\"fw\":\"%s\",\"board\":\"%s\"},"
        "\"sys\":{\"heap\":%u,\"uptime\":%lu,\"ip\":\"%s\",\"sta\":%d}}",
        heap,
        (int)cfg.camera, camGetName(), (int)st, kStateNames[st], batt,
        tel.recTimeSeconds, tel.dataValid ? "true" : "false", tel.model,
        recorderDesiredRecording() ? "true" : "false",
        recorderSwitchOn() ? "true" : "false",
        cfg.recordOnArm ? "true" : "false",
        recorderLastRcValue(),
        cfg.auxChannelIndex, cfg.rcThresholdUs, cfg.debounceMs,
        cfg.osdSlot[0], cfg.osdSlot[1], cfg.osdSlot[2], cfg.osdSlot[3],
        osdSlotText(0), osdSlotText(1), osdSlotText(2), osdSlotText(3),
        (cfg.wifiSwitchCh <= 15) ? (int)cfg.wifiSwitchCh : -1,
        _up ? "true" : "false",
        cfg.scanAll ? "true" : "false",
        safeErr,
        cams, pending,
        scanResultsIsScanning() ? "true" : "false",
        fc.fcAlive ? "true" : "false", fc.armed ? "true" : "false",
        fc.vbat10, fc.rssi / 10, fc.cycleTimeUs,
        fcApiVersion(), fcFirmwareVersion(), fcBoardName(),
        heap, millis() / 1000UL, _ipStr,
        WiFi.softAPgetStationNum());
    (void)w;  // Truncation would only clip trailing '}' — buffer sized with headroom

    _server.sendHeader("Cache-Control", "no-store");
    _server.send(200, "application/json", buf);
}

static void sendJsonError(const char *msg) {
    char buf[128];
    snprintf(buf, sizeof(buf), "{\"ok\":false,\"error\":\"%s\"}", msg);
    _server.send(400, "application/json", buf);
}

static void handleSettingsPost() {
    String body = _server.arg("plain");

    if (!jsonHas(body, "camera") && !jsonHas(body, "auxChannel") &&
        !jsonHas(body, "recordOnArm") && !jsonHas(body, "ssid") &&
        !jsonHas(body, "slots") && !jsonHas(body, "wifiSwitch") &&
        !jsonHas(body, "scanAll")) {
        sendJsonError("no recognized keys");
        return;
    }

    ShutterSettings &cfg = settingsGet();
    bool apNeedsRestart = false;

    // Camera brand
    if (jsonHas(body, "camera")) {
        long cam = jsonGetNum(body, "camera");
        if (cam == CAMERA_GOPRO && cfg.camera != CAMERA_GOPRO) {
            camSetCamera(CAMERA_GOPRO);
        } else if (cam == CAMERA_DJI && cfg.camera != CAMERA_DJI) {
            camSetCamera(CAMERA_DJI);
        } else if (cam != CAMERA_DJI && cam != CAMERA_GOPRO) {
            sendJsonError("invalid camera type");
            return;
        }
    }

    // Record switch
    if (jsonHas(body, "auxChannel")) {
        long ch = jsonGetNum(body, "auxChannel");
        if (ch < 0 || ch > 15) { sendJsonError("channel out of range"); return; }
        cfg.auxChannelIndex = (uint8_t)ch;
    }
    if (jsonHas(body, "threshold")) {
        long t = jsonGetNum(body, "threshold");
        if (t < 1200 || t > 1800) { sendJsonError("threshold out of range"); return; }
        cfg.rcThresholdUs = (uint16_t)t;
    }
    if (jsonHas(body, "debounce")) {
        long d = jsonGetNum(body, "debounce");
        if (d < 50 || d > 1000) { sendJsonError("debounce out of range"); return; }
        cfg.debounceMs = (uint16_t)d;
    }

    // Behaviour toggles
    if (jsonHas(body, "recordOnArm"))
        cfg.recordOnArm = jsonGetBool(body, "recordOnArm");
    if (jsonHas(body, "stopOnDisarm"))
        cfg.stopOnDisarm = jsonGetBool(body, "stopOnDisarm");

    // "Show all nearby devices" toggle (NVS-persisted, no AP restart).
    if (jsonHas(body, "scanAll"))
        cfg.scanAll = jsonGetBool(body, "scanAll");

    // Wi-Fi radio switch channel (-1 or 255 = disabled)
    if (jsonHas(body, "wifiSwitch")) {
        long ch = jsonGetNum(body, "wifiSwitch");
        if ((ch >= 0 && ch <= 15) || ch == -1) {
            cfg.wifiSwitchCh = (ch == -1) ? 255 : (uint8_t)ch;
        } else {
            sendJsonError("wifi switch channel out of range");
            return;
        }
    }

    // OSD slots
    for (uint8_t s = 0; s < 4; s++) {
        char key[8];
        snprintf(key, sizeof(key), "slot%d", s);
        if (jsonHas(body, key)) {
            long v = jsonGetNum(body, key);
            if (v < 0 || v >= OSD_SLOT_COUNT) {
                sendJsonError("invalid slot content");
                return;
            }
            cfg.osdSlot[s] = (uint8_t)v;
        }
    }

    // Wi-Fi credentials
    if (jsonHas(body, "ssid")) {
        String ssid = jsonGetStr(body, "ssid");
        ssid.trim();
        if (ssid.length() < 1 || ssid.length() > 32) {
            sendJsonError("SSID must be 1-32 chars");
            return;
        }
        strlcpy(cfg.apSsid, ssid.c_str(), sizeof(cfg.apSsid));
        apNeedsRestart = true;
    }
    if (jsonHas(body, "pass")) {
        String pass = jsonGetStr(body, "pass");
        pass.trim();
        if (pass.length() > 0 && pass.length() < 8) {
            sendJsonError("password must be empty or 8-64 chars");
            return;
        }
        strlcpy(cfg.apPass, pass.c_str(), sizeof(cfg.apPass));
        apNeedsRestart = true;
    }

    settingsSave();
    DBG("WEB: settings saved");

    if (apNeedsRestart) {
        _server.send(200, "application/json",
                     "{\"ok\":true,\"apRestart\":true}");
        delay(500);                       // Let the response flush
        webInit();                        // Re-raise SoftAP with new creds
        return;
    }

    _server.send(200, "application/json", "{\"ok\":true}");
}

static void handleCommand() {
    String body = _server.arg("plain");
    String cmd = jsonGetStr(body, "cmd");

    if (cmd == "start") {
        recorderManualStart();
        _server.send(200, "application/json", "{\"ok\":true}");
    } else if (cmd == "stop") {
        recorderManualStop();
        _server.send(200, "application/json", "{\"ok\":true}");
    } else if (cmd == "reboot") {
        _server.send(200, "application/json", "{\"ok\":true}");
        delay(400);
        ESP.restart();
    } else {
        sendJsonError("unknown command");
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// Saved-camera registry endpoints:  POST /api/camera {"select":i} | {"remove":i}
// ──────────────────────────────────────────────────────────────────────────────

static void handleCameraPost() {
    String body = _server.arg("plain");

    if (jsonHas(body, "scan")) {
        // {"scan": true} — user-initiated discovery scan.
        // Refuse to start a second scan while one is in progress so the
        // 5 s window is not split across two competing jobs on the radio.
        if (scanResultsIsScanning()) {
            // Graceful degradation: tell the UI we are already scanning,
            // don't throw 400.
            _server.send(200, "application/json", "{\"ok\":true,\"already\":true}");
            return;
        }
        camStartUserScan();
        _server.send(200, "application/json", "{\"ok\":true}");
    } else if (jsonHas(body, "select")) {
        long idx = jsonGetNum(body, "select", -1);
        if (idx < 0 || !camRegistrySelect((uint8_t)idx)) {
            sendJsonError("invalid camera index");
            return;
        }
        camKick();   // Stop scanning, connect to the selected MAC right away
        _server.send(200, "application/json", "{\"ok\":true}");
    } else if (jsonHas(body, "remove")) {
        long idx = jsonGetNum(body, "remove", -1);
        if (idx < 0 || !camRegistryRemove((uint8_t)idx)) {
            sendJsonError("invalid camera index");
            return;
        }
        // Also disconnect BLE if removing the active camera
        shutdownActiveBackend();
        _server.send(200, "application/json", "{\"ok\":true}");
    } else if (jsonHas(body, "pair")) {
        // "pair" body: {"mac":"AA:BB:...","type":0|1}
        String mac = jsonGetStr(body, "mac");
        long type = jsonGetNum(body, "type", -1);
        if (!mac.length() || (type != CAMERA_DJI && type != CAMERA_GOPRO)) {
            sendJsonError("pair: mac and type required");
            return;
        }
        // Check if device is currently visible in scan results (online check)
        uint8_t dcount = 0;
        const ScanResult *dr = camRegistryDiscovered(dcount);
        bool isOnline = false;
        char nameBuf[24] = "";
        for (uint8_t i = 0; i < dcount; i++) {
            if (strcasecmp(dr[i].mac, mac.c_str()) == 0 && dr[i].type == (uint8_t)type) {
                isOnline = true;
                strlcpy(nameBuf, dr[i].name, sizeof(nameBuf));
                break;
            }
        }
        // Don't allow pairing with offline devices
        if (!isOnline) {
            sendJsonError("Cannot pair: device is offline or not in range");
            return;
        }
        if (!camRegistrySave((uint8_t)type, mac.c_str(),
                              nameBuf[0] ? nameBuf : mac.c_str())) {
            sendJsonError("pair: registry full or invalid");
            return;
        }
        // Find the newly-saved entry's index and select+kick it.
        for (uint8_t i = 0; i < settingsGet().camCount; i++) {
            if (strcasecmp(settingsGet().cams[i].mac, mac.c_str()) == 0 &&
                settingsGet().cams[i].type == (uint8_t)type) {
                camRegistrySelect(i);
                camKick();
                break;
            }
        }
        _server.send(200, "application/json", "{\"ok\":true}");
    } else {
        sendJsonError("expected scan, select, remove, or pair");
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// MSP passthrough — lets the Web UI talk MSP directly to the FC.
// Read-only allowlist: safe introspection commands only.  This is the
// foundation for a future browser-side "configurator-lite" panel.
// ──────────────────────────────────────────────────────────────────────────────

static bool mspCmdAllowed(uint16_t cmd) {
    static const uint16_t kAllowed[] = {
        MSP_API_VERSION,   // 1
        MSP_FC_VARIANT,    // 2
        MSP_FC_VERSION,    // 3
        MSP_BOARD_INFO,    // 4
        5,                 // MSP_BUILD_INFO
        MSP_STATUS,        // 101
        104,               // MSP_MOTOR
        MSP_RC,            // 105
        108,               // MSP_RAW_GPS? (harmless read)
        109,               // MSP_ALTITUDE
        MSP_ANALOG,        // 110
        116,               // MSP_BOXNAMES
        MSP_BOXIDS,        // 119
        130,               // MSP_BATTERY_STATE
    };
    for (size_t i = 0; i < sizeof(kAllowed) / sizeof(kAllowed[0]); i++) {
        if (kAllowed[i] == cmd) return true;
    }
    return false;
}

static void handleMspPost() {
    String body = _server.arg("plain");
    long cmd = jsonGetNum(body, "cmd", -1);

    if (cmd < 0 || cmd > 255) {
        sendJsonError("missing/invalid cmd");
        return;
    }
    if (!mspCmdAllowed((uint16_t)cmd)) {
        sendJsonError("command not in read-only allowlist");
        return;
    }

    // Flush any stale bytes, then send the request and wait for the reply.
    // Safe here: we run inside loop()'s call stack (single-threaded), and the
    // main-loop parser simply resyncs on '$' afterwards.
    while (Serial1.available()) Serial1.read();

    mspSendRequest((uint8_t)cmd);

    MspMessage msg;
    uint32_t started = millis();
    bool got = false;
    while (millis() - started < MSP_RESPONSE_TIMEOUT_MS) {
        while (Serial1.available()) {
            uint8_t b = Serial1.read();
            if (mspParseByte(b, msg)) {
                fcStatusFeed(msg);          // Keep live stats fresh
                if ((uint16_t)msg.cmd == (uint16_t)cmd && msg.valid && !msg.isError) {
                    got = true;
                    break;
                }
            }
        }
        if (got) break;
        delay(2);
        yield();
    }

    if (!got) {
        _server.send(504, "application/json",
                     "{\"ok\":false,\"error\":\"FC timeout\"}");
        return;
    }

    // Hex-encode the payload.
    static char hex[MSP_MAX_PAYLOAD_SIZE * 3 + 4];
    size_t o = 0;
    for (uint8_t i = 0; i < msg.payloadSize; i++) {
        o += snprintf(hex + o, sizeof(hex) - o, "%02X", msg.payload[i]);
    }
    hex[o] = '\0';

    char out[192];
    snprintf(out, sizeof(out),
             "{\"ok\":true,\"cmd\":%u,\"len\":%u,\"payload\":\"%s\"}",
             (unsigned)msg.cmd, (unsigned)msg.payloadSize, hex);
    _server.send(200, "application/json", out);
}

// ──────────────────────────────────────────────────────────────────────────────
// Scan Results Endpoint
// ──────────────────────────────────────────────────────────────────────────────

static void handleScanResults() {
    uint8_t dcount = 0;
    const ScanResult *dr = camRegistryDiscovered(dcount);

    static char buf[4096];
    char *p = buf;
    size_t left = sizeof(buf);

    size_t w = snprintf(p, left, "{\"scanning\":%s,\"results\":[",
                        scanResultsIsScanning() ? "true" : "false");
    p += w;
    left -= w;

    for (uint8_t i = 0; i < dcount; i++) {
        const char *typeStr = (dr[i].type == CAMERA_GOPRO) ? "GoPro" : "DJI Osmo";
        w = snprintf(p, left,
            "%s{\"mac\":\"%s\",\"name\":\"%s\",\"t\":\"%s\",\"r\":%d}",
            i ? "," : "",
            dr[i].mac,
            dr[i].name[0] ? dr[i].name : "",
            typeStr,
            dr[i].rssi);
        p += w;
        if (w >= left) break;
        left -= w;
    }

    snprintf(p, left, "]}");
    _server.send(200, "application/json", buf);
}

static void redirectToRoot() {
    _server.sendHeader(String("Location"), String("http://") + _ipStr + "/", true);
    _server.send(302, "text/plain", "");
}

// ── OS captive-portal probe handlers ─────────────────────────────────────────
// Each OS probes a known URL to detect "internet available".  Answering these
// with their expected SUCCESS bodies makes Windows/iOS/Android mark the
// network as usable immediately — no scary errors, no blocked popups.  Any
// other hostname still lands on our UI via the onNotFound redirect.

static const char NCSI_SUCCESS[] =
    "Microsoft Connect Test";

static void handleProbeConnectTest() {          // Windows: /connecttest.txt
    _server.send(200, "text/plain", NCSI_SUCCESS);
}

static void handleProbeNcsi() {                 // Windows legacy: /ncsi.txt
    _server.send(200, "text/plain", "Microsoft NCSI");
}

static void handleProbe204() {                  // Android: /generate_204
    _server.send(204, "text/plain", "");
}

static void handleProbeApple() {                // iOS/macOS: /hotspot-detect.html
    _server.send(200, "text/html",
                 "<HTML><HEAD><TITLE>Success</TITLE></HEAD><BODY>Success</BODY></HTML>");
}

// ──────────────────────────────────────────────────────────────────────────────
// Lifecycle
// ──────────────────────────────────────────────────────────────────────────────

void webStart() {
    const ShutterSettings &cfg = settingsGet();
    if (_up) return;   // Already running

    WiFi.persistent(false);              // Keep Wi-Fi creds out of NVS
    WiFi.mode(WIFI_AP);
    delay(100);

    // Deterministic AP address: 192.168.4.1/24 (matches UI + captive portal).
    IPAddress localIp(192, 168, 4, 1);
    IPAddress gateway(192, 168, 4, 1);
    IPAddress subnet(255, 255, 255, 0);
    WiFi.softAPConfig(localIp, gateway, subnet);

    bool havePass = (strlen(cfg.apPass) >= 8);
    bool ok;
    if (havePass) {
        ok = WiFi.softAP(cfg.apSsid, cfg.apPass);
    } else {
        ok = WiFi.softAP(cfg.apSsid);   // Open network
    }
    if (!ok) {
        DBG("WEB: SoftAP failed — retrying once");
        delay(500);
        ok = havePass ? WiFi.softAP(cfg.apSsid, cfg.apPass)
                      : WiFi.softAP(cfg.apSsid);
    }
    if (!ok) {
        DBG("WEB: SoftAP failed twice!");
        _up = false;
        return;
    }

    strlcpy(_ipStr, localIp.toString().c_str(), sizeof(_ipStr));

    // Captive DNS: every hostname resolves to us.
    _dns.stop();
    _dns.setErrorReplyCode(DNSReplyCode::NoError);
    if (!_dns.start(53, "*", localIp)) {
        DBG("WEB: captive DNS failed to start");
    }

    _server.stop();
    _server.on("/",               HTTP_GET,  handleRoot);
    _server.on("/api/status",     HTTP_GET,  handleStatus);
    _server.on("/api/settings",   HTTP_POST, handleSettingsPost);
    _server.on("/api/camera",     HTTP_POST, handleCameraPost);
    _server.on("/api/command",    HTTP_POST, handleCommand);
    _server.on("/api/msp",        HTTP_POST, handleMspPost);
    _server.on("/api/scan",       HTTP_GET,  handleScanResults);

    // OS connectivity probes → answer with SUCCESS bodies (see handlers above).
    _server.on("/connecttest.txt",              HTTP_GET, handleProbeConnectTest);
    _server.on("/ncsi.txt",                     HTTP_GET, handleProbeNcsi);
    _server.on("/generate_204",                 HTTP_GET, handleProbe204);
    _server.on("/gen_204",                      HTTP_GET, handleProbe204);
    _server.on("/hotspot-detect.html",          HTTP_GET, handleProbeApple);
    _server.on("/library/test/success.html",    HTTP_GET, handleProbeApple);
    // Anything else (any hostname, any path) → our UI.
    _server.onNotFound(redirectToRoot);

    _server.begin();
    _up = true;

    DBG("WEB: AP '%s' up — http://%s/ (open=%s)",
        cfg.apSsid, _ipStr, havePass ? "false" : "true");
}

void webStop() {
    if (!_up) return;
    _dns.stop();
    _server.stop();
    WiFi.softAPdisconnect(true);
    WiFi.mode(WIFI_OFF);          // Powers down the Wi-Fi radio (BLE unaffected)
    _up = false;
    DBG("WEB: Wi-Fi powered off (radio switch)");
}

void webInit() {
    // Boot-time entry point.  Always starts the AP so the user can never be
    // locked out; a configured radio switch turns it off once RC data flows.
    webStart();
}

void webUpdate() {
    if (!_up) return;
    _dns.processNextRequest();
    _server.handleClient();
}

const char* webApIp() { return _ipStr; }
bool webIsUp()        { return _up; }
